### ISSUE TITLE
Implement system `elot-ell-grek-latn-743-2001` (ELOT 743:2001)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#222]
This issue is to implement the transliteration system of `elot-ell-grek-latn-743-2001`.

This system is based on `elot-ell-grek-latn-743-1982` with minor differences explained in Wikipedia:

> As revised in 2001, ELOT 743 provides for the uncommon characters to be given (in Greek) as $ for stigma, + for koppa, and / for sampi. These symbols are not given lower-case equivalents.[13]

**Comment by opoudjis** [comment]
Wrong. The ELOT 2001 version is massively different to ELOT 1982.

**Comment by ronaldtse** [comment]
~~I can't find the source spec. Argh.~~

Found it: https://docplayer.gr/docview/18/849832/#file=/storage/18/849832/849832.pdf

Attached here: 
[ΕΛΟΤ 743-2001.pdf](https://github.com/riboseinc/interscript/files/4238611/743-2001.pdf)

**Comment by opoudjis** [comment]
ELOT 2001 has two transcription schemes. The transcription (reversable) is new, and is what is in Wikipedia. The transliteration is identical to what is in 1982. There is confusion, because Greek passports seem to have skipped from transliteration to transcription, and people say "this is ELOT 2001 not ELOT 1982"; but that's misleading: it's ELOT 2001 TR, and ELOT 2001 TL is identical to ELOT 1982.

**Comment by ronaldtse** [comment]
Just to clarify, as described by the UN 1987 document, ELOT 743 1982 is likely to have both transcription and transliteration systems. 

![](https://user-images.githubusercontent.com/11865/75045636-9b2c0080-54fe-11ea-85c1-fe1dcd6592ae.png)
