### ISSUE TITLE
Implement GOST 16876-71:1983 Russian (`gost-rus-cyrl-latn-16876-71-1983`)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#294]
I was able to find GOST 1983 here: [7th_UNCSGN_econf.91_3_Add1.html.zip](https://github.com/interscript/interscript/files/4692813/7th_UNCSGN_econf.91_3_Add1.html.zip)
* it is the OCR'ed from this file: https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/7th-uncsgn-docs/econf/7th_UNCSGN_econf.91_3_Add1.pdf

We should Implement GOST 16876-71:1983 Russian (`gost-rus-cyrl-latn-16876-71-1983`)

<img width="515" alt="Screen Shot 2020-05-28 at 9 55 37 AM" src="https://user-images.githubusercontent.com/11865/83090328-1f2bf080-a0cb-11ea-89c7-f918b95aeead.png">
<img width="489" alt="Screen Shot 2020-05-28 at 9 55 48 AM" src="https://user-images.githubusercontent.com/11865/83090332-205d1d80-a0cb-11ea-9fd1-a4bad4956631.png">

<img width="483" alt="Screen Shot 2020-05-28 at 9 59 02 AM" src="https://user-images.githubusercontent.com/11865/83090416-4e426200-a0cb-11ea-9177-dbc365ca3284.png">
<img width="518" alt="Screen Shot 2020-05-28 at 9 57 52 AM" src="https://user-images.githubusercontent.com/11865/83090420-50a4bc00-a0cb-11ea-9983-4cdce3ec62bd.png">

_Originally posted by @ronaldtse in https://github.com/interscript/interscript/issues/76#issuecomment-635052191_

**Comment by CAMOBAP** [comment]
@ronaldtse I have found original GOST document here http://vsegost.com/Catalog/45/45002.shtml 

I have noted that for some letters it allow to select different results:
for example: Щ -> `Šč` or `Ŝ`

If I will compare attached screenshots with http://vsegost.com/Catalog/45/45002.shtml it looks inconsistent, because something's it select the first variant (without brackets) or second (within brackets)

@ronaldtse what is your opinion should we follow https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/7th-uncsgn-docs/econf/7th_UNCSGN_econf.91_3_Add1.pdf or http://vsegost.com/Catalog/45/45002.shtml ?

If you ask me if we need real `GOST 16876-71` we should check  http://vsegost.com/Catalog/45/45002.shtml 

P.S. How do we really know that `GOST 1983` and `GOST 16876-71` refer to the same document?

**Comment by ronaldtse** [comment]
> P.S. How do we really know that GOST 1983 and GOST 16876-71 refer to the same document?

It was stated in one of the UNGEGN documents.

I think GOST 16876-71 provides two systems, the first has no choice, the second allows choice of the rules.

Have you found any discrepancy between https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/7th-uncsgn-docs/econf/7th_UNCSGN_econf.91_3_Add1.pdf and http://vsegost.com/Catalog/45/45002.shtml ?

**Comment by CAMOBAP** [comment]
> Have you found any discrepancy between

Formally no

But to give you a more complete picture about `GOST 16876-71`:
 - It defines two tables: one with diacritics, second without
 - Even for the one with diacritics, it allows multiple choice
 - This is why I was a bit confused by UNGEGN doc (the doc from top comment), it selects first variant for all letters except `Щ`. For this letter, it selects the second variant: `Šč` instead of first one: `Ŝ`

Let me confirm again that formally this isn't an issue

**Comment by CAMOBAP** [comment]
@ronaldtse  I have found relation `GOST 1983` and `GOST 16876-71`

16 April 1982 - the year when this GOST was officially introduced
13 May 1983 - contains an updated table and according to it it 100% equal to the one which attached it top comment

Official document
https://rosreestr.ru/upload/documenty/doc_169.doc

13 May 1983 edition eliminate pluralism of translation, so staring from it there is exists only one way to 'convert' characters

**Comment by CAMOBAP** [comment]
PR is ready for review https://github.com/interscript/interscript/pull/296

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
