### ISSUE TITLE
Fix Rpsec error (master branch)

### ISSUE THREAD

**Issue by phuonghuynh** [interscript/interscript-ruby#326]
/cc @ronaldtse 

We getting failed cases in Rspec.
[rspec_results.zip](https://github.com/interscript/interscript/files/5008186/rspec_results.zip)

**Comment by ronaldtse** [comment]
<img width="296" alt="Screen Shot 2020-08-01 at 1 12 38 AM" src="https://user-images.githubusercontent.com/11865/89059618-18a04a80-d394-11ea-88a6-eb90d11eac79.png">

https://github.com/interscript/interscript/actions/runs/188562558

@phuonghuynh there is no failure in master branch... see GHA. This latest failure on windows is due to network issues.

**Comment by ronaldtse** [comment]
@phuonghuynh you have to see the GHA workflow to see how to setup the Python usage.

**Comment by ronaldtse** [comment]
https://github.com/interscript/interscript/blob/c07282af44ba1d3ccaa0ca8c55d74f3a5b6139c3/.github/workflows/test.yml#L47-L73

**Comment by phuonghuynh** [comment]
Thanks @ronaldtse , my bad, good now,

> Finished in 34.9 seconds (files took 1.85 seconds to load)
> 3615 examples, 0 failures

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh , hope this will be fixed in interscript-api.
