### ISSUE TITLE
Verify UN Arabic 1972 system rule for `i` (and other rules)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#355]
From #347 

> 2- Ar Riyāḑ "الرِياض"
> ي with ِ before it is transliterated to ī in 2017
> but in UN it's just a normal i, does this mean that in 1972 ي with ِ was just an i

From UN 2017 system:
http://www.eki.ee/wgrs/rom1_ar.pdf

<img width="825" alt="Screen Shot 2020-08-29 at 12 32 57 AM" src="https://user-images.githubusercontent.com/11865/91591228-3068ef80-e98f-11ea-9c9c-0a444eb42dd0.png">

It is not described in the UN 1972 system that `i` is transliterated differently.

<img width="878" alt="Screen Shot 2020-08-29 at 12 33 15 AM" src="https://user-images.githubusercontent.com/11865/91591256-3ced4800-e98f-11ea-86ed-ae99b7e2bf2e.png">

**Comment by ronaldtse** [comment]
https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_C3_R.6_Rev.2.pdf

This is the original UN 1972 Arabic system.

[E_Conf61_C3_R.6_Rev.2.pdf](https://github.com/interscript/interscript/files/5143281/E_Conf61_C3_R.6_Rev.2.pdf)

<img width="610" alt="Screen Shot 2020-08-29 at 1 03 33 AM" src="https://user-images.githubusercontent.com/11865/91593841-7922a780-e993-11ea-9b69-a7e007c92f37.png">
<img width="481" alt="Screen Shot 2020-08-29 at 1 03 53 AM" src="https://user-images.githubusercontent.com/11865/91593872-82ac0f80-e993-11ea-92ed-4c669ac526db.png">
<img width="472" alt="Screen Shot 2020-08-29 at 1 04 01 AM" src="https://user-images.githubusercontent.com/11865/91593881-8770c380-e993-11ea-8843-b1b735db93d2.png">
<img width="609" alt="Screen Shot 2020-08-29 at 1 04 20 AM" src="https://user-images.githubusercontent.com/11865/91593910-92c3ef00-e993-11ea-9f2c-580d0a802bec.png">

@AhMohsen46 as you can see, in UN 1972, ي with ِ  was just an `i`.

**Comment by ronaldtse** [comment]
@AhMohsen46 could you also verify that the 1972 system implemented fully adheres to this document? Thanks!

UPDATE: I've also reported this missing difference back to UNGEGN, in case they want to update the http://www.eki.ee/wgrs/rom1_ar.pdf document.

**Comment by AhMohsen46** [comment]
I've been comparing the doc for the last hour
I can see it's almost 100% matching, except for one rule related to Ar Riyad
as per the screenshot attached,  ya' `ي` preceded by kasra ` ِ ` should be  `ī`   
however, on UNstats, Ar Riyāḑ "الرِياض" 
also, in the image, you can find the rule in the last line
in المَدِينة it's transliterated to `Al Madīnah`
it's done correctly
and in the first line in the screenshot, it's `Ar Riyāḑ` , so I think they might be dealing with الرياض without kasra under `ر`
am almost like 99% certain الرِياض has a kasra under `ر`
maybe it's not and am missing this, I've also asked a linguist I know
but if they have a linguist to validate whether "الرِياض has a kasra under `ر`" or not, it'll be perfect
also here's a link from arabic word reference https://www.almaany.com/ar/dict/ar-ar/%D8%B1%D9%8A%D8%A7%D8%B6/

otherwise, I guess for all the other rules we're matching the document 
![image](https://user-images.githubusercontent.com/34799755/91637308-e1ab6c00-ea07-11ea-8aea-5a8aee55f6f8.png)


as for خ "kh" as addressed in this [comment](https://github.com/interscript/interscript/issues/347#issuecomment-680401109)
I can see in the doc it's either kh with a line under k or normal kh, on UN site, it's without a line under kh, so am going to follow UN site "kh" with no lines, unless our communication point to UNGEN says something else

![image](https://user-images.githubusercontent.com/34799755/91637621-0b659280-ea0a-11ea-9136-6ec95a43c738.png)

**Comment by ronaldtse** [comment]
This is the official answer from UNGEGN:

> I see the point but the same table was also attached to the 1972 system, so there is no change.
> 
> Arabic script here is somewhat ambiguous as the combination shown in rule 9 can be interpreted either as ī (long i) or i + y.  To be precise, in the first instance the consonant 'y' (ي) is not accompanied by any diacritical signs while in the second instance the consonant 'y' should be accompanied by a short vowel sign, indicating that 'y' starts a new syllable.
> 
> So a hypothetical syllable rīt would look like this: رِيت.
> 
> And riyāḑ is like this: رِيَاض.
> 
> The same ambiguousness is with rule 10 in the same table that can be either ū or u + w.

Is this issue resolved? If so please close this, thanks!

**Comment by AhMohsen46** [comment]
It makes perfect sense, thanks for the great help!, for ī part, I can say we're okay

But did they comment on "kh" case too please?
```
خ is kh on UN site
on 2017 it's kẖ
so my assumption it should have been changed from kḩ, but if UN is perfectly fitting 1972, so it's not
Sudan Captial:
الخرطوم
Al Khurţūm
and city in saudi arabia
خــــميس مشــــيط - Khamīs Mushayţ

```

**Comment by AhMohsen46** [comment]
https://github.com/interscript/interscript/pull/363 for i, as soon as we're done with kh, we can close this
@ronaldtse

**Comment by ronaldtse** [comment]
I requested clarification for the kh issue, will update when I get a reply.

**Comment by AhMohsen46** [comment]
Thanks @ronaldtse [url](https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/2nd-uncsgn-docs/E_Conf61_C3_R.6_Rev.2.pdf) here it's optional to be with underbars or without, but I can see on https://unstats.un.org/unsd/geoinfo/geonames/ it's all with no underbars; if unstats is following 1972 as I knew, it should be with underbars, or it might mean that underbars occur in a very limited cases

**Comment by ronaldtse** [comment]
Clarified in #364 , closing this now.
