### ISSUE TITLE
Implement ISO 15919:2001 Pali in Thai and Burmese script

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#517]
Implement the following ISO 15919 systems. Once these systems are implemented all ISO 15919 systems are complete.

```
iso-pli-thai-latn-15919-2001,ISO 15919:2001 Information and documentation -- Transliteration of Devanagari and related Indic scripts into Latin characters,iso,iso-639-2,pli,Thai,Latn,15919-2001,<<ISO15919>>,,,
iso-pli-mymr-latn-15919-2001,ISO 15919:2001 Information and documentation -- Transliteration of Devanagari and related Indic scripts into Latin characters,iso,iso-639-2,pli,Mymr,Latn,15919-2001,<<ISO15919>>,,,
```

_Originally posted by @ronaldtse in https://github.com/interscript/interscript/issues/406#issuecomment-703990616_

**Comment by bilashsaha** [comment]
@ronaldtse The document [ISO 15919:2001](https://www.chatranjali.fr/Scripts/Standards/ISO15919.pdf) does not have enough information to cover `Thai` and `Burmese` transliteration. 

For `iso-pli-thai-latn-15919-2001`:
We can inherit [ISO 11940:1998](https://github.com/interscript/interscript/blob/master/maps/iso-tha-Thai-Latn-11940-1998.yaml) and I can add some Pali examples of Thai script.

**Comment by ronaldtse** [comment]
> @ronaldtse The document [ISO 15919:2001](https://www.chatranjali.fr/Scripts/Standards/ISO15919.pdf) does not have enough information to cover `Thai` and `Burmese` transliteration.

I see! 

> For `iso-pli-thai-latn-15919-2001`:
> We can inherit [ISO 11940:1998](https://github.com/interscript/interscript/blob/master/maps/iso-tha-Thai-Latn-11940-1998.yaml) and I can add some Pali examples of Thai script.

Yes please, that would be great. Please also add in the description/notes on how the system was built.

------

Also, have you seen the Annexes? How should we approach these?

Clause 10: Uniform tranlsiteration
Clause 11: transliterating scheme for limited character set
Clause 12: Indic schemes <-> Perso-Arabic characters

**Comment by bilashsaha** [comment]
@ronaldtse While doing the transliteration map for the languages. I read and checked the Annexes and extracted important information related to a language from there and put them in the note section. I had also used the Uniform transliteration while mapping the transliteration maps for every languages.

For the Perso-Arabic characters, I think I can extract the corresponding characters for every language script and put them with the mapping rules and add some examples using them.

the `Transliteration table for limited (7-bit) character set` is for 7-bit characters but we are not using 7bit characters for representing our transliteration. So that table does not have any importance for us.

**Comment by bilashsaha** [comment]
PR : https://github.com/interscript/interscript/pull/522 to cover `iso-pli-thai-latn-15919-2001`

**Comment by bilashsaha** [comment]
PR: https://github.com/interscript/interscript/pull/523 to cover clauses regarding `Perso-Arabic characters`

**Comment by ronaldtse** [comment]
Thanks @bilashsaha ! Let's close this ticket then.
