### ISSUE TITLE
Implement system `bgnpcgn-ara-arab-latn-1956` (BGN/PCGN Romanization System -- Arabic (1956)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#60]
This issue is to implement the transliteration system of bgnpcgn-ara-arab-latn-1956.

This system is referred in the GeoNames database as `ara_Arab2Latn_BGN_1956`, with the system title 'BGN/PCGN Romanization System -- Arabic (1956)'.

 Tests should rely on the data extracted for the `ara_Arab2Latn_BGN_1956` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
@manuel489 Would you be able to help encode this map? Spec located here: Thanks!

https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/858000/ROMANIZATION_OF_ARABIC.pdf

Ping @nbh707

**Comment by manuelfuenmayor** [comment]
Ok @ronaldtse

**Comment by manuelfuenmayor** [comment]
Hi @ronaldtse,
Apparently, there is an inconsistency between the romanization character : `th` and its Unicode value: `0073+0304`.

![romanization-capture1](https://user-images.githubusercontent.com/33627611/74169635-fd812900-4c01-11ea-9324-864966ad750e.JPG)

Using an unicode converter like: https://www.branah.com/unicode-converter

For `\u0073\u0304`, I get the character `s̄` instead of `th`. (The unicode value for `th` is `\u0074\u0068`.)

In this case, should I use the unicode value (`\u0073\u0304`) for mapping or the romanization character (`th`)?

**Comment by ronaldtse** [comment]
I think it is `th`, and this is an error in the BGN/PCGN document.

In these columns, notice that `th` and `dh` both have `...+0304`. However, `kh` and `sh` have `...+0068`.

<img width="212" alt="Screen Shot 2020-02-11 at 12 40 37 AM" src="https://user-images.githubusercontent.com/11865/74169969-212a8a80-4c67-11ea-87a4-4cc3645c139d.png">

So I checked another transliteration document (https://transliteration.eki.ee/pdf/Arabic_2.2.pdf), and it seems that 062B is always transliterated as a `t`, `th` or a modified `t`.

<img width="857" alt="Screen Shot 2020-02-11 at 12 40 53 AM" src="https://user-images.githubusercontent.com/11865/74169998-2b4c8900-4c67-11ea-9603-454ca9a2448e.png">

This makes me think that it `...+0304` is an error (for both `th` and `dh`).

**Comment by ronaldtse** [comment]
Actually, I stand corrected. It is possible that instead of `th` they meant `s̄` and instead of `dh` they meant `z̄`. Let me clarify with them.

**Comment by ronaldtse** [comment]
Under "Special Rules" at the end, it says:

> When the definite article precedes a word beginning with one of the “sun letters” t, th, d, dh, r, z, s, sh, ş, ḑ, ţ, z,̧ l, or n

So this alludes to `th` and `dh`...

**Comment by manuelfuenmayor** [comment]
Yeah, in addition, if we look at the provided example:

![romanization-capture2](https://user-images.githubusercontent.com/33627611/74172844-54d5c800-4c07-11ea-8e97-761be5ceeb7a.JPG)

We can see that the phrase only contains `th` (instead of `s̄`). Which makes me think that `th` is the correct character.

Oh, and talking about examples. In the example columns, there are "pointed" script and "unpointed" script in Arabic language:

![romanization-capture3](https://user-images.githubusercontent.com/33627611/74173142-f3fabf80-4c07-11ea-8d45-3b0b39560485.JPG)

Which one should I use for encoding the tests?

**Comment by ronaldtse** [comment]
@manuel489 we have to use the "Pointed Script". "Unpointed Script" omits short vowels so transliteration by mapping isn't possible.

**Comment by manuelfuenmayor** [comment]
> @manuel489 we have to use the "Pointed Script". "Unpointed Script" omits short vowels so transliteration by mapping isn't possible.

Ok, understood.

Map added in https://github.com/riboseinc/interscript/pull/236

**Comment by nbh707** [comment]
th is correct. This is the sound like "th" in "the"

**Comment by nbh707** [comment]
In some dialects it is pronounced like "t" so that would account for the instances of "t"

**Comment by nbh707** [comment]
As for pointed text, there are a few entries in the BGN file that do have the vowels written, or some of the vowels written. But the majority do not. So we need to use the transliteration in the BGN file to determine what vowels are missing in the original Arabic.

**Comment by ronaldtse** [comment]
Original spec: [BGN_Romanization_Guide_1964_arabic_1956.pdf](https://github.com/interscript/interscript/files/5180770/BGN_Romanization_Guide_1964_arabic_1956.pdf)

**Comment by ronaldtse** [comment]
This task is being done in #371 .

**Comment by AhMohsen46** [comment]
issue for two example given in the doc https://github.com/interscript/interscript/issues/386
