### ISSUE TITLE
Implement system `ses-ara-arab-latn-1930` (Survey of Egypt Arabic System)

### ISSUE THREAD

**Issue by ronaldtse** [interscript/interscript-ruby#68]
This issue is to implement the transliteration system of ses-ara-arab-latn-1930.

This system is referred in the GeoNames database as `ara_Arab2Latn_SES_1930`, with the system title 'Survey of Egypt Arabic System'.

 Tests should rely on the data extracted for the `ara_Arab2Latn_SES_1930` system in https://github.com/riboseinc/geonames-transliteration-data .

**Comment by ronaldtse** [comment]
<img width="915" alt="Screen Shot 2020-08-26 at 1 04 11 AM" src="https://user-images.githubusercontent.com/11865/91205388-0ec1fb00-e738-11ea-9744-8d109689b545.png">

**Comment by AhMohsen46** [comment]
@ronaldtse since the mapping here is from latin to latin, how about that, we inherit from 2017, and add post-rules to do this mapping?

would be more intuitive?
or should I track back and override characters mapping?, am okay doing any of them, they are more or less the same for me

second question, for letters having multiple mappings like

s = s(c) 
or 
q = q(k)

this might be helpful for reverse mapping, but for "from arabic to latin" mapping, would you recommend taking the first choice?

or should I keep the both
like having it this way
"س":
        -"s"
        -"c"

**Comment by ronaldtse** [comment]
It would be better to do a direct Arabic to Latin mapping. The documentation on top was just to indicate the comparison between the two systems. 

When there are multiple transliteration rules, let’s just use the first rule. I know the second rule may be used depending on context (which may be used when there is machine learning).

**Comment by AhMohsen46** [comment]
PR https://github.com/interscript/interscript/pull/357

**Comment by AhMohsen46** [comment]
related issue https://github.com/interscript/interscript/issues/362 // not blocking
